collections:
  Latest Episodes:
    smart_filter:
      sort_by: epiepisode_release.desc
    sort_title: "!Latest Episodes"
    sync_mode: sync
    visible_library: true
    visible_home: true
    visible_shared: true