collections:
  Latest Episodes:
    smart_filter:
      type: show
      sort_by: episode_air_date.desc
    sort_title: "!Latest Episodes"
    sync_mode: sync
    visible_library: true
    visible_home: true
    visible_shared: true
