metadata:
  'Star Wars: The Clone Wars':
    seasons:
      1:
        title: A Galaxy Divided
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      2:
        title: Rise of the Bounty Hunters
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      3:
        title: Secrets Revealed
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      4:
        title: Battle Lines
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      5:
        title: Death and Destruction
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      6:
        title: The Lost Missions
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      7:
        title: The Final Season
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
