metadata:
  'Star Wars: The Clone Wars':
    seasons:
      Specials:
        episodes:
          1:
            user_rating:
      1:
        title: Season 1
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
          13:
            user_rating:
          14:
            user_rating:
          15:
            user_rating:
          16:
            user_rating:
          17:
            user_rating:
          18:
            user_rating:
          19:
            user_rating:
          20:
            user_rating:
          21:
            user_rating:
          22:
            user_rating:
      2:
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
          13:
            user_rating:
          14:
            user_rating:
          15:
            user_rating:
          16:
            user_rating:
          17:
            user_rating:
          18:
            user_rating:
          19:
            user_rating:
          20:
            user_rating:
          21:
            user_rating:
          22:
            user_rating:
      3:
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
          13:
            user_rating:
          14:
            user_rating:
          15:
            user_rating:
          16:
            user_rating:
          17:
            user_rating:
          18:
            user_rating:
          19:
            user_rating:
          20:
            user_rating:
          21:
            user_rating:
          22:
            user_rating:
      4:
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
          13:
            user_rating:
          14:
            user_rating:
          15:
            user_rating:
          16:
            user_rating:
          17:
            user_rating:
          18:
            user_rating:
          19:
            user_rating:
          20:
            user_rating:
          21:
            user_rating:
          22:
            user_rating:
      5:
        title: Season 5
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
          13:
            user_rating:
          14:
            user_rating:
          15:
            user_rating:
          16:
            user_rating:
          17:
            user_rating:
          18:
            user_rating:
          19:
            user_rating:
          20:
            user_rating:
      6:
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
          13:
            user_rating:
      7:
        title: Season 7
        episodes:
          1:
            user_rating:
          2:
            user_rating:
          3:
            user_rating:
          4:
            user_rating:
          5:
            user_rating:
          6:
            user_rating:
          7:
            user_rating:
          8:
            user_rating:
          9:
            user_rating:
          10:
            user_rating:
          11:
            user_rating:
          12:
            user_rating:
