metadata:
  'Star Wars: The Clone Wars':
    seasons:
      1:
        title: A Galaxy Divided
        episodes:
          1:
            title: Ambush
            summary: Great leaders inspire greatness in others. While trying to negotiate a treaty for the Republic, Jedi Master Yoda and a handful of clone troopers are ambushed by a Separatist army.
          2:
            title: Rising Malevolence
            summary: Belief is not a matter of choice, but of conviction. An attack by a devastating new Separatist weapon – the powerful starship Malevolence – leaves Jedi Master Plo Koon and his clone troopers struggling to survive until Anakin Skywalker and Ahsoka can find them.
          3:
            title: Shadow of Malevolence
            summary: Easy is the path to wisdom for those not blinded by ego. Anakin utilizes new long-range Y-wing bombers to lead a strike on General Grievous' warship.
          4:
            title: Destroy Malevolence
            summary: A plan is only as good as those who see it through. Padmé Amidala and C-3PO are taken hostage by General Grievous, leaving Anakin and Obi-Wan to save the Senator and complete the destruction of the Malevolence.
          5:
            title: Rookies
            summary: The best confidence builder is experience. Alone on a distant outpost, clone officers Rex and Cody must inspire their rookie unit to believe in themselves to stave off a Droid Commando invasion.
          6:
            title: Downfall of a Droid
            summary: Trust in your friends, and they'll have reason to trust in you. During a battle with the Separatists R2-D2 is lost and they must find him before the Separatists do because of the military secrets locked inside the droid.
          7:
            title: Duel of the Droids
            summary: You hold onto friends by keeping your heart a little softer than your head. R2-D2 is being held at General Grievous' secret listening post. Ahsoka, Anakin and replacement droid R3-S6 go on a dual rescue and sabotage mission.
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      2:
        title: Rise of the Bounty Hunters
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      3:
        title: Secrets Revealed
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      4:
        title: Battle Lines
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      5:
        title: Death and Destruction
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      6:
        title: The Lost Missions
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
      7:
        title: The Final Season
        episodes:
          1:
            title:
            summary: 
          2:
            title:
            summary: 
          3:
            title:
            summary: 
          4:
            title:
            summary: 
          5:
            title:
            summary: 
          6:
            title:
            summary: 
          7:
            title:
            summary: 
          8:
            title:
            summary: 
          9:
            title:
            summary: 
          10:
            title:
            summary: 
          11:
            title:
            summary: 
          12:
            title:
            summary: 
          13:
            title:
            summary: 
          14:
            title:
            summary: 
          15:
            title:
            summary: 
          16:
            title:
            summary: 
          17:
            title:
            summary: 
          18:
            title:
            summary: 
          19:
            title:
            summary: 
          20:
            title:
            summary: 
          21:
            title:
            summary: 
          22:
            title:
            summary: 
