collections:
  Recently Aired TV Shows:
    smart_filter:
      limit: 50
      all:
        has_episodes_aired: 30  # Shows with episodes aired in last 30 days
    collection_order: added.desc
    sync_mode: sync
    visible_home: true
    summary: TV shows with recently aired episodes, sorted by most recent.