######################################################
#              Trakt Dynamic Collections             #
######################################################

templates:
  trakt:
    optional:
      - show
    trakt_list_details: <<trakt_user_lists>>
    tvdb_show: <<show>>

dynamic_collections:
  #Create collections based on the Trakt lists associated with the authenticated user.
  Trakt List Collections:
    template: trakt
    type: trakt_user_lists
    data: me
    exclude: Stand-Up
    template_variables:
      show:
        Tom and Jerry:
          - 72860    # Tom and Jerry 1940
