######################################################
#              TMDB Dynamic Collections              #
######################################################

templates:
  tmdb:
    optional:
      - movie
      - summary
      - sort
      - order
      - minimum
      - mode
    tmdb_collection_details: <<tmdb_collection>>
    tmdb_movie: <<movie>>
    summary: <<summary>>
    sort_title: <<sort>>
    collection_order: <<order>>
    collection_mode: <<mode>>
    minimum_items: <<minimum>>

dynamic_collections:
  TMDb Collections:
    template: tmdb
    type: tmdb_collection
    addons: 
      8091:        # Alien
        - 135416   # Prometheus
      86066:       # Despicable Me
        - 544669   # Minions
      1241422:     # Miraculous
        - 822306   # Miraculous World
      34055:       # Pokémon
        - 661025   # Pokémon Advanced
        - 661026   # Pokémon Diamond and Pearl
        - 661028   # Pokémon Best Wishes (Black and White)
        - 661029   # Pokémon XY
        - 661031   # Pokémon Alternate Continuity
      86860:       # Scooby-Doo
        - 633815   # The Mystery Begins
      115575:      # Star Trek: Alternate Reality                                          
        - 151      # Star Trek: The Original Series                                               
        - 115570   # Star Trek: The Next Generation
      8650:        # Transformers
        - 939352   # Rise of the Beasts
      489724:      # Trolls
        - 1184152  # Trolls Holiday
      529:         # Wallace & Gromit
        - 1403306  # Wallace & Gromit Movies
      748:         # X-Men
        - 453993   # The Wolverine
        - 448150   # Deadpool
    remove_prefix: The
    remove_suffix: Collection
    title_override:
      750822: The Addams Family
      125574: The Amazing Spider-Man
      1231053: The Bad Guys
      948485: The Batman
      722971: Benoit Blanc Mysteries
      743824: The Christmas Chronicles 
      420: The Chronicles of Narnia
      86066: Despicable Me & Minions
      263: The Dark Knight
      126125: The Expendables
      9485: Fast & Furious
      230: The Godfather
      87251: The Good Witch
      121938: The Hobbit
      131635: The Hunger Games
      325470: Lego Movies
      1004630: Lego Star Wars
      119: The Lord of the Rings
      110021: The Magnificent Seven
      2344: The Matrix
      742536: The Meg
      1733: The Mummy
      893731: PAW Patrol
      735384: Poirot
      256322: The Purge
      86860: Scooby-Doo!
      394204: The Snowman
      275402: SpongeBob SquarePants
      115575: Star Trek
      721111: U.S. Marshals
      1304326: Watchmen (Animated)
      627517: The Wizard of Oz
      683698: Zombies
    template_variables:
      movie:
        8091:          # Alien
          - 945961     # Alien Romulus
        1231053:       # Bad Guys
          - 981424     # Maraschino Ruby
          - 1046032    # Bad Holiday
        466463:        # Descendants
          - 805411     # The Royal Wedding
        9485:          # Fast & Furious
          - 384018     # Hobbs & Shaw
        1241:          # Harry Potter
          - 899082     # 20th Anniversary
        9888:          # Home Alone
          - 134375     # Holiday Heist
          - 654974     # Home Sweet Home Alone
        8354:          # Ice Age
          - 46247      # No Time for Nuts
          - 387893     # Egg-Scapade
          - 79218      # Mammoth Christams
        70068:         # IP Man
          - 658009     # Kung Fu Master
          - 643413     # Four Kings
          - 450001     # Master Z
          - 751391     # Crisis Time
          - 44249      # Legend is Born
          - 182127     # Final Fight
          - 44865      # The Grandmaster
        328:           # Jurassic Park
          - 630322     # Battle at Big Rock
        77816:         # Kung Fu Panda
          - 50393      # King Fu Panda Holiday   
          - 81003      # Secrets of the Masters
        325470:        # Lego Movie
          - 324849     # Lego Batman Movie
        14740:         # Madagascar
          - 25472      # Merry Madagascar
          - 161143     # Madly Madagascar
          - 10258      # Penguins Christmas Caper
          - 270946     # Penguins of Madagascar
        2344:          # The Matrix
          - 55931      # Animatrix
        99606:         # Mean Girls
          - 673593     # Mean Girls Musical
        822306:        # Miraculous World
          - 496450     # Ladybug & Cat Noir, The Movie
        1733:          # The Mummy
          - 9334       # Scorpion King
        304:           # Ocean's
          - 402900     # Ocean's Eight
        34055:         # Pokémon
          - 36897      # Mewtwo Returns
        708816:        # Power Rangers
          - 305470     # Power Rangers (2017)
          - 1068141    # Once & Always
        521226:        # Quiet Place
          - 762441     # Quiet Place Day One
        656:           # Saw
          - 602734     # Spiral
        2150:          # Shrek
          - 13394      # Shrek the Halls
          - 25523      # Ghost of Lord Farquaad
          - 48466      # Scared Shrekless
          - 51256      # Shrektacular
        627517:        # Wizard of Oz
          - 13155      # Return to Oz
          - 68728      # Oz the Great and Powerful
        17255:         # Resident Evil
          - 460458     # Welcome to Racoon City
        86486:         # Spy Kids
          - 790493     # Armageddon
        10:            # Star Wars
          - 330459     # Rogue One 
          - 348350     # Solo
        8650:          # Transformers
          - 424783     # Bumblebee
        748:           # X-Men
          - 340102     # New Mutants
      sort:
        750822: Addams Family
        125574: Amazing Spider-Man
        1231053: Bad Guys
        948485: Batman
        334996: Batman, Son of
        743824: Christmas Chronicles
        201873: Christmas Story
        420: Chronicles of Narnia
        263: Dark Knight
        126125: Expendables
        230: Godfather
        87251: Good Witch
        121938: Hobbit
        131635: Hunger Games
        119: Lord of the Rings
        110021: Magnificent Seven
        2344: Matrix
        742536: Meg
        1733: Mummy
        256322: Purge
        394204: Snowman
        627517: Wizard of Oz
      order:
        10: alpha       # Star Wars
      summary:
        1241422: "Miraculous is a series of movies based on the Miraculous: Tales of Ladybug & Cat Noir by Thomas Astruc."   # Miraculous
        115575: Space... the final frontier. Star Trek is an American science fiction media franchise created by Gene Roddenberry, which began with the eponymous 1960s television series.   # Star Trek
      #mode:
      #minimum:
    exclude:
      - 100693    # 101 Dalmatians (Animated)                                         
      - 124916    # 101 Dalmatians (Live-Action) 
      - 86027     # Aladdin
      - 748401    # Aladdin (Live Action)
      - 312735    # Annie
      - 422834    # Ant-Man
      - 573693    # Aquaman
      - 86311     # The Avengers
      - 87250     # Bambi
      - 379475    # Batman Beyond
      - 421904    # Batman DCAU
      - 153010    # Beauty and the Beast                                                
      - 529892    # Black Panther
      - 131295    # Captain America
      - 623911    # Captain Marvel
      - 87118     # Cars
      - 8819      # Casper   
      - 1028525   # Charlie Brown
      - 55419     # Cinderella                                                              
      - 837007    # Cruella   
      - 593251    # Death of Superman
      - 618529    # Doctor Strange
      - 531799    # Enchanted              
      - 178117    # The Emperor's New Groove   
      - 137697    # Finding Nemo                                            
      - 100970    # The Fox and the Hound
      - 386382    # Frozen
      - 535313    # Godzilla
      - 284433    # Guardians of the Galaxy
      - 978459    # Hercules
      - 97456     # The Hunchback of Notre Dame  
      - 468222    # The Incredibles
      - 131292    # Iron Man                                                     
      - 285564    # Jarhead                                                       
      - 307637    # Jingle All the Way                                                     
      - 97459     # The Jungle Book   
      - 97460     # Lady and the Tramp
      - 97461     # Lilo & Stitch                                                             
      - 94032     # The Lion King                                                                       
      - 762512    # The Lion King (Reboot)                                                     
      - 33085     # The Little Mermaid 
      - 531331    # Maleficent            
      - 209131    # Man of Steel
      - 527439    # Mary Poppins
      - 137696    # Monsters, Inc.
      - 87236     # Mulan
      - 55422     # Peter Pan
      - 136214    # Pocahontas                                                                  
      - 57971     # The Rescuers
      - 53159     # The Santa Clause                                                                                                       
      - 1006443   # Scooby-Doo
      - 869205    # Scooby-Doo WWE
      - 762458    # Scooby-Doo Zombie Island   
      - 912503    # Shang-Chi                                                                 
      - 724848    # Shazam!
      - 334996    # Son of Batman
      - 531241    # Spider-Man (Avengers)                                                                                                          
      - 531242    # Suicide Squad   
      - 290933    # Superman/Batman
      - 729425    # Team Thor   
      - 131296    # Thor       
      - 123694    # Timon and Pumbaa
      - 10194     # Toy Story
      - 109608    # Van Helsing
      - 468552    # Wonder Woman
      - 404825    # Wreck-It Ralph
      # Cached errors
      - 1011336   # Eternals
      - 1051005   # Greyhound
      - 1246022   # Peanuts
      - 1272685   # Muppets
      - 1329522   # Dollars Trilogy
      - 1079241   # Clifford the Big Red Dog
      - 861429    # Jungle Cruise
