######################################################
#                  Chart Collections                 #
######################################################

templates:
  sort:
    collection_order: custom
    smart_label:
      all:
        label: <<smart_label>>
  imdb:
    imdb_chart: <<chart>>_<<library_type>>s
    sort_title: ++++<<collection_name>>
  tmdb:
    default:
      limit: 100
      limit_<<key>>: <<limit>>
      chart: <<key>>
    tmdb_<<chart>>: <<limit_<<key>>>>
    sort_title: ++++<<collection_name>>
  trakt:
    default:
      limit: 100
      limit_<<key>>: <<limit>>
    trakt_chart:
      chart: <<key>>
      limit: <<limit_<<key>>>>
    sort_title: +++<<collection_name>>

collections:
  IMDb Popular:
    template: 
      - name: sort
      - name: imdb
        chart: popular
    summary: Popular <<library_type>>s as determined by IMDb users.
  IMDb Top 250:
    template: 
      - name: sort
      - name: imdb
        chart: top
    summary: The top 250 best <<library_type>>s of all time based on IMDb user ratings.
  TMDb Popular:
    variables:
      key: popular
    template:
      - name: sort
      - name: tmdb
    summary: Popular <<library_type>>s as determined by TMDb users.
  TMDb Top Rated:
    variables:
      key: top
    template:
      - name: sort
      - name: tmdb
        chart: top_rated
    summary: Top rated <<library_type>>s based on TMDb user ratings.
  TMDb Trending:
    variables:
      key: trending
    template:
      - name: sort
      - name: tmdb
        chart: trending_weekly
    summary: <<library_type>>s trending this week on TMDb.
  Trakt Popular:
    variables:
      key: popular
    template:
      - name: sort
      - name: trakt
    summary: Popular <<library_type>>s as determined by Trakt users.
  Trakt Recommended:
    variables:
      key: recommended
    template:
      - name: sort
      - name: trakt
    summary: <<library_type>>s recommended this week on Trakt.
  Trakt Trending:
    variables:
      key: trending
    template:
      - name: sort
      - name: trakt
    summary: <<library_type>>s trending this week on Trakt.
