######################################################
#                  Chart Collections                 #
######################################################

templates:
  sort:
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
    sort_title: ++++<<collection_name>>
    schedule: weekly(monday)

collections:
  IMDb Top 250:
    imdb_chart: top_<<library_type>>s
    smart_label:
      sort_by: audience_rating.desc
      all:
        label: <<smart_label>>
    sort_title: ++++<<collection_name>>
    summary: The top 250 best <<library_type>>s of all time based on IMDb user ratings.
 
  TMDb Trending:
    template: {name: sort}
    tmdb_trending_weekly: 100
    summary: Collection of <<library_type>>s trending this week on TMDb, updated every Monday.
 
  Trakt Trending:
    template: {name: sort}
    trakt_chart:
      chart: trending
      limit: 100
    summary: Collection of <<library_type>>s trending this week on Trakt, updated every Monday.
