######################################################
#               Streaming Collections                #
######################################################

templates:
  streaming:
    conditionals:
      discover_region:
        conditions:
          - originals_only: false
            value: <<region>>
      discover_with:
        conditions:
          - originals_only: false
            value: <<key>>
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
    mdblist_list: https://mdblist.com/lists/plexmetamanager/<<url_key>>-originals
    tmdb_discover:
      with_watch_providers: <<discover_with>>
      watch_region: <<discover_region>>
    summary: Collection of <<library_type>>s currently streaming on <<collection_name>>.
    sort_title: ++<<collection_name>>

dynamic_collections:
  Streaming:
    template: streaming
    type: custom
    data:
      350: Apple TV+
      337: Disney+
      1899: Max
      8: Netflix
      9: Prime Video
    title_format: <<key_name>>
    template_variables:
      url_key:
        350: appletv
        337: disney
        1899: max
        8: netflix
        9: amazon
